export { createConsoleInterceptor } from './console-interceptor';
export type { ConsoleInterceptorHandle } from './console-interceptor';
export { createNetworkInterceptor } from './network-interceptor';
export type { NetworkInterceptorHandle } from './network-interceptor';
export { createNavigationInterceptor } from './navigation-interceptor';
export type { NavigationCallback } from './navigation-interceptor';
export { DomDiffer } from './dom-differ';
export type { DiffResult } from './dom-differ';
export { SnapshotStore } from './snapshot-store';
export { createEventCapture } from './event-capture';
export type { EventCaptureHandle, SnapshotCallback } from './event-capture';
export { RecordingEngine } from './recording-engine';
